style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: "https://github.com/pjuanda/terraform-module-templates"
options:
  commits:
     filters:
       Type:
         - feat
         - fix
         - refactor
  commit_groups:
     title_maps:
       feat: Features
       fix: Bug Fixes
       refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
